version: "3.3"
services:
#  db:
#    image: mysql:5.7
#    volumes:
#      - db_data:/var/lib/mysql
#    restart: always
#    env_file:
#      - docker/env.defaults
#    ports:
#      - "3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/app
    env_file:
      - docker/env.defaults
    environment:
#      MYSQL_HOST: db
      XDEBUG_ENABLE:
      XDEBUG_REMOTE_HOST:
      XDEBUG_CONFIG:
      PHP_IDE_CONFIG:
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    depends_on:
#      - db
#    env_file:
#      - docker/env.defaults
#    environment:
#      PMA_HOST: db
#      PMA_USER: root
#    ports:
#      - "8082:80"

#volumes:
#  db_data:
